### ISSUE TITLE
[project]: project3

### ISSUE THREAD

**Issue by AshwinSri23** [Carleton-Blueprint/bluebot-dev#22]
### Name of organization

asda

### Name of VP Projects

asda

### Organization Tag

asdasd

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshwinSri23** [comment]
ASDASDAS

**Comment by Oopsiepoopsie** [comment]
aaa

**Comment by Oopsiepoopsie** [comment]
ssss
